project/Dependencies.scala, scripts/ci.sh, src/it/java/org/testcontainers/containers/ExasolDockerContainer.java
Additionally, some minor dependency and plugin version bumps.
=> Bump Spark version to 2.4.0

.travis.yml, build.sbt, project/Dependencies.scala, project/build.properties, project/plugins.sbt, project/project/plugins.sbt, sbtx, scripts/ci.sh, src/it/scala/com/exasol/spark/ColumnPruningSuite.scala, src/it/scala/com/exasol/spark/LoadSuite.scala, src/it/scala/com/exasol/spark/ReservedKeywordsSuite.scala, src/it/scala/com/exasol/spark/SaveSuite.scala, src/main/scala/com/exasol/spark/DefaultSource.scala, src/main/scala/com/exasol/spark/rdd/ExasolRDD.scala, src/main/scala/com/exasol/spark/util/Converter.scala, src/main/scala/com/exasol/spark/util/Types.scala, src/test/scala/com/exasol/spark/DefaultSourceSuite.scala
- Adds Scala version 2.12 in order to compile Spark 2.4+ versions.
- Updates several dependencies and travis Spark and Scala versions.
Fixes #38.
=> Cross compile using Scala 2.12+

README.md
- Adds a prerequisite section in order to use the connector.
- Adds description why `Connection refused` error might happen due to closed sub-connection ports.  
Fixes #42.
=> Update readme with prerequisite section and additional FAQ.

README.md
sparkSession has now write function but dataframe has
=> fix spark write example inside README

README.md, project/Compilation.scala, project/Dependencies.scala, project/plugins.sbt
Provided overview of runtime and test libraries with their corresponding licenses. Similarly, lists compiler plugins used for development.
=> Added dependency list to readme.

README.md, src/main/scala/com/exasol/spark/util/ExasolConfiguration.scala, src/main/scala/com/exasol/spark/util/ExasolConnectionManager.scala, src/test/scala/com/exasol/spark/util/ExasolConnectionManagerSuite.scala
=> #76: Added JDBC connection options

.travis.yml, build.sbt, doc/changes/changelog.md, doc/changes/changes_0.3.2.md, project/Dependencies.scala, scripts/ci.sh, src/it/java/org/testcontainers/containers/ExasolDockerContainer.java, src/main/scala/com/exasol/spark/util/ExasolConnectionManager.scala
=> #78: Updated Exasol JDBC version to 7.0.0.

README.md, dependencies.md, doc/changes/changes_0.1.0.md, doc/changes/changes_0.1.1.md, doc/changes/changes_0.1.2.md, doc/changes/changes_0.1.3.md, doc/changes/changes_0.2.0.md, doc/changes/changes_0.2.1.md, doc/changes/changes_0.3.0.md, doc/changes/changes_0.3.1.md, doc/changes/changes_0.3.2.md, doc/user_guide/user_guide.md, pom.xml
=> #104: Fixed artifact name

doc/changes/changes_1.2.0.md, doc/user_guide/user_guide.md, pom.xml, src/main/scala/com/exasol/spark/rdd/ExasolRDD.scala, src/main/scala/com/exasol/spark/util/ExasolConfiguration.scala, src/main/scala/com/exasol/spark/util/ExasolConnectionManager.scala, src/main/scala/com/exasol/spark/util/Filters.scala, src/test/scala/com/exasol/spark/it/AbstractTableQueryIT.scala, src/test/scala/com/exasol/spark/it/BaseIntegrationTest.scala, src/test/scala/com/exasol/spark/it/LoadIT.scala, src/test/scala/com/exasol/spark/it/SaveOptionsIT.scala, src/test/scala/com/exasol/spark/it/SparkDataImportIT.scala, src/test/scala/com/exasol/spark/util/ExasolConnectionManagerSuite.scala, src/test/scala/com/exasol/spark/util/FiltersSuite.scala
=> #103: Added support certificate fingerprint option

doc/changes/changes_1.2.0.md, pom.xml
=> #112: Updated log4j dependency version

.github/workflows/ci-build.yml, .github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/release_droid_print_quick_checksum.yml, .github/workflows/release_droid_release_on_maven_central.yml, .github/workflows/release_droid_upload_github_release_assets.yml, dependencies.md, doc/changes/changes_1.2.0.md, pom.xml, src/test/scala/com/exasol/spark/it/BaseIntegrationTest.scala, tools/createReleasePom.sh
=> #111: Fixed issues with cross releasing with updated release droid workflows

doc/changes/changes_1.2.1.md, doc/development/developer_guide.md
added note about doing releases
=> updated release date

.gitattributes, .github/workflows/ci-build.yml, .project-keeper.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_1.2.2.md, pk_generated_parent.pom, pom.xml, release_config.yml, src/test/scala/com/exasol/spark/SparkSessionSetup.scala, src/test/scala/com/exasol/spark/it/BaseIntegrationTest.scala
=> #121: Upgrade dependencies

.github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/release_droid_print_quick_checksum.yml, .github/workflows/release_droid_release_on_maven_central.yml, .github/workflows/release_droid_upload_github_release_assets.yml
=> Release 1.2.3

.github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/release_droid_print_quick_checksum.yml, .github/workflows/release_droid_release_on_maven_central.yml, .github/workflows/release_droid_upload_github_release_assets.yml, .project-keeper.yml, dependencies.md, doc/changes/changelog.md, doc/changes/changes_1.3.0.md, pk_generated_parent.pom, pom.xml
=> #141: Added release artifact for Scala 2.12 variant

dependencies.md, doc/changes/changelog.md, doc/changes/changes_1.2.2.md, doc/changes/changes_1.4.1.md, pk_generated_parent.pom, pom.xml
=> #151: Fixed dependency vulnerabilities

error_code_config.yml, src/main/java/com/exasol/spark/s3/Constants.java, src/main/java/com/exasol/spark/s3/DelegatingWriteBuilder.java, src/main/java/com/exasol/spark/s3/ExasolBatchWrite.java, src/main/java/com/exasol/spark/s3/ExasolS3ScanBuilder.java, src/main/java/com/exasol/spark/s3/ExasolS3Table.java, src/main/java/com/exasol/spark/s3/ExasolWriteBuilderProvider.java, src/main/java/com/exasol/spark/s3/Option.java, src/main/java/com/exasol/spark/s3/S3ClientFactory.java, src/test/java/com/exasol/spark/s3/AbstractDataWritingIntegrationTest.java, src/test/java/com/exasol/spark/s3/S3DataWritingIT.java
=> #160: Add support for writing to Exasol database using S3 as intermediate storage

.github/workflows/release_droid_upload_github_release_assets.yml, doc/changes/changes_1.5.0.md
=> #176: Fixed artifact sha256sum files upload bug

.github/workflows/broken_links_checker.yml, .github/workflows/pk-verify.yml, dependencies.md, doc/changes/changes_1.5.0.md, doc/development/developer_guide.md, error_code_config.yml, exasol-jdbc/pom.xml, exasol-s3/error_code_config.yml, exasol-s3/pom.xml, exasol-s3/src/main/java/com/exasol/spark/s3/ExasolBatchWrite.java, exasol-s3/src/main/java/com/exasol/spark/s3/ExasolS3Table.java, exasol-s3/src/main/java/com/exasol/spark/s3/ExasolWriteBuilderProvider.java, exasol-s3/src/main/java/com/exasol/spark/s3/S3BucketKeyPathProvider.java, exasol-s3/src/main/java/com/exasol/spark/s3/S3FileSystem.java, exasol-s3/src/main/java/com/exasol/spark/s3/UUIDS3BucketKeyPathProvider.java, exasol-s3/src/test/java/com/exasol/spark/s3/ExasolWriteBuilderProviderIT.java, parent-pom/pk_generated_parent.pom, parent-pom/pom.xml
=> #164: Added validation check before writing to intermediate location

.project-keeper.yml, dependencies.md, doc/changes/changes_2.0.0.md, exasol-jdbc/pk_generated_parent.pom, exasol-jdbc/pom.xml, exasol-s3/pk_generated_parent.pom, exasol-s3/src/main/java/com/exasol/spark/s3/S3BucketKeyPathProvider.java, exasol-s3/src/main/java/com/exasol/spark/s3/S3FileSystem.java, exasol-s3/src/main/java/com/exasol/spark/s3/UUIDS3BucketKeyPathProvider.java
=> #188: Fixed maven central deployment bug

dependencies.md, doc/changes/changes_2.1.2.md, exasol-jdbc/pom.xml, parent-pom/pom.xml
Closes https://github.com/exasol/spark-connector/issues/206
=> Fix CVE-2023-42503 and update deps

.gitattributes, .github/workflows/ci-build-next-java.yml, .github/workflows/ci-build.yml, .github/workflows/dependencies_check.yml, .github/workflows/pk-verify.yml, .github/workflows/release_droid_prepare_original_checksum.yml, .github/workflows/release_droid_print_quick_checksum.yml, .github/workflows/release_droid_release_on_maven_central.yml, .github/workflows/release_droid_upload_github_release_assets.yml, .project-keeper.yml, .vscode/settings.json, dependencies.md, doc/changes/changelog.md, doc/changes/changes_2.2.1.md, doc/development/developer_guide.md, exasol-jdbc/pom.xml, exasol-jdbc/src/test/scala/com/exasol/spark/it/BaseIntegrationTest.scala, exasol-s3/pom.xml, exasol-s3/src/test/java/com/exasol/spark/BaseIntegrationSetup.java, exasol-s3/src/test/java/com/exasol/spark/s3/S3IntegrationTestSetup.java, parent-pom/pom.xml, pom.xml
=> #230: Upgrade dependencies to fix vulnerabilities
